# Numpy basics

## Creating numpy arrays

In [1]:
import numpy as np
a = np.array((1, 2, 3, 4), float)
a

array([1., 2., 3., 4.])

In [3]:
list1 = [[1, 2, 3], [4,5,6]]
list1

[[1, 2, 3], [4, 5, 6]]

In [1]:
import numpy as np
import pandas as pd

a = np.array((1, 2, 3, 4), float)
print (pd.DataFrame(a))
a

     0
0  1.0
1  2.0
2  3.0
3  4.0


array([1., 2., 3., 4.])

In [12]:
import numpy as np
import pandas as pd

list1 = [[1, 2, 3], [4,5,6]]
df = pd.DataFrame(list1)

df.style

In [2]:
import numpy as np
import pandas as pd

list1 = [[1, 2, 3], [4,5,6]]
foo = np.array(list1, float)
df = pd.DataFrame(foo)

df.style

In [14]:
import numpy as np
import pandas as pd

list1 = [[1, 2, 3], [4,5,6]]

mat = np.array(list1, complex)

df = pd.DataFrame(mat)
df.style

In [4]:
import numpy as np
a = np.arange(15)
foo = np.array(a, float)
df = pd.DataFrame(foo)

df.style

In [9]:
b = np.linspace(-4.5, 4.5, 11)
foo = np.array(b, float)
df = pd.DataFrame(foo)

df.style

In [15]:
c = np.zeros((3, 3), float)
c[0,0] = 1
c[1,1] = 1
c[2,2] = 1
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
scale = 100
c = np.zeros((scale,scale), float)
for x in range(0, scale):
    c[x,x] = 1
pd.DataFrame(c).style

In [16]:
c = np.identity(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
b=np.array([-1. , -0.5,  0. ,  0.5,  1. ])
np.diag(b, k=1)

array([[ 0. , -1. ,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. , -0.5,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0.5,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  1. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ]])

In [25]:
np.diag(np.ones(5))

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
c = np.zeros((4, 6), float)
pd.DataFrame(c).style

In [27]:
d = np.ones((2, 4))
pd.DataFrame(d).style

## Non-numeric data

In [30]:
a = np.array(['foo', 'foo-bar'])
a

array(['foo', 'foo-bar'], dtype='<U7')

In [30]:
dna = 'AAAGTCTGAC'
a = np.array(dna, dtype='c')
a

array([b'A', b'A', b'A', b'G', b'T', b'C', b'T', b'G', b'A', b'C'],
      dtype='|S1')

In [35]:
dna = 'AAAGTCTGAC'
a = np.array(dna, dtype='c')
pd.DataFrame(a).style

## Indexing and slicing arrays

In [36]:
mat = np.array([[1, 2, 3], [4, 5, 6]])
pd.DataFrame(mat).style

In [43]:
mat[0,2]

3

In [44]:
mat[0,2]=999
pd.DataFrame(mat).style

In [45]:
mat[1,-2]

5

In [48]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [51]:
print(a[2:])

[2 3 4]


In [55]:
a[-3:-1]

array([2, 3])

In [60]:
a[1:3]=-1
a

array([ 0, -1, -1,  3,  4])

In [66]:
a = np.zeros((4,4))
a[1:3, 1:3] = 3
pd.DataFrame(a).style

In [73]:
a = np.zeros((4,4))
a[1:3, 1:3] = 3

b = a[1:3,1:]
a[2,2] = 1234
pd.DataFrame(b).style
#pd.DataFrame(a).style

In [76]:
a = np.zeros((4,4))
a[1:3, 1:3] = 3

b = a[1:3,1:].copy()
a[2,2] = 1234
pd.DataFrame(b).style
#pd.DataFrame(a).style

In [80]:
a = np.zeros((4,4))
a[1:3, 1:3] = 3

b = a[1:3,1:]
#a[2,2] = 1234
#pd.DataFrame(b).style
b[0,0] = 111
pd.DataFrame(a).style

## Array manipulation

In [84]:
mat = np.array([[1,2,3], [4,5,6]])
mat

array([[1, 2, 3],
       [4, 5, 6]])

In [88]:
x = mat.reshape(3,2)
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [89]:
mat.ravel()

array([1, 2, 3, 4, 5, 6])

In [110]:
mat1 = np.array([[1,2,3],[4,5,6]])
mat2 = np.array([[7,8,9],[10,11,12]])
mat3 = np.array([[1,1,1],[2,2,2]])
x = np.concatenate((mat1,mat2,mat3))
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [ 1,  1,  1],
       [ 2,  2,  2]])

In [112]:
x[1,2]

6

In [118]:
a = np.split(x, 3, axis=1)
pd.DataFrame(a[2]).style

## Array operations

In [124]:
a = np.array([1.0, 2.0, 3.0]) * 2.0
pd.DataFrame(a).style

In [126]:
import math
a = np.linspace(-math.pi, math.pi, 8)
pd.DataFrame(a).style

In [132]:
np.sin(a)

array([-1.22464680e-16, -7.81831482e-01, -9.74927912e-01, -4.33883739e-01,
        4.33883739e-01,  9.74927912e-01,  7.81831482e-01,  1.22464680e-16])

In [142]:
b = np.linspace(0,360, 9)
b
c = b * math.pi/180
c
np.sin(c)

array([ 0.00000000e+00,  7.07106781e-01,  1.00000000e+00,  7.07106781e-01,
        1.22464680e-16, -7.07106781e-01, -1.00000000e+00, -7.07106781e-01,
       -2.44929360e-16])

## Advanced Indexing

In [166]:
x = np.arange(10,1,-1)
pd.DataFrame(x).style

In [167]:
references = np.array([3,3,1,8])
y = x[references]
pd.DataFrame(y).style

In [148]:
x

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [155]:
m = x > 4
m

array([ True,  True,  True,  True,  True,  True, False, False, False])

In [168]:
a = np.linspace(-5,5,9)
b = a >= 0
a[b]
np.sqrt(a[b]) 

array([0.        , 1.11803399, 1.58113883, 1.93649167, 2.23606798])

Other languages x^2, python x**2

In [180]:
data = np.arange(100, dtype=np.float) 
pd.DataFrame(data).style

In [181]:
data = np.empty(100, dtype=np.float) 
pd.DataFrame(data).style